version: "3.8"

services:

  database:
      container_name: databaseapi
      image: postgres
      environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mercadoapi
      ports:
        - "5432:5432"
        
  pgadmin:
      container_name: pgadminapi
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "15000:80"
